# 矩陣(Matrix)

## 矩陣加法

In [2]:
# 載入套件
import numpy as np

# 矩陣
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])

# 加法
print(A + B)

[[7 7 7]
 [7 7 7]]


In [3]:
# 減法
print(A - B)

[[-5 -3 -1]
 [ 1  3  5]]


## 矩陣乘法

In [4]:
# 載入套件
import numpy as np

# 矩陣
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[9,8],
              [7,6],
              [5,4],
             ])

# 乘法
print(A @ B)

[[ 38  32]
 [101  86]]


In [27]:
# 乘法：A x B != B x A

A = np.array([[1,2],
              [4,5]])
B = np.array([[9,8],
              [7,6],
             ])

print(A @ B)
print()
print(B @ A)
print()
print('A x B != B x A')

[[23 20]
 [71 62]]

[[41 58]
 [31 44]]

A x B != B x A


## 轉置矩陣

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

# 轉置矩陣
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
# 兩次轉置，會回復成原來的矩陣
print(A.T.T)

[[1 2 3]
 [4 5 6]]


## 反矩陣

In [41]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             ])
print(np.linalg.inv(A))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [31]:
A.shape

(3, 3)

## A x A反矩陣 = 單位矩陣(I)

In [36]:
# A @ A反矩陣 = 單位矩陣(I)
A = np.array([[9,8],
              [7,6],
             ])

print(np.around(A @ np.linalg.inv(A)))

[[1. 0.]
 [0. 1.]]


In [38]:
# A @ A反矩陣 = 單位矩陣(I)
A = np.array([[1,2,3],
              [4,7,6],
              [7,9,9],
             ])

print(np.around(A @ np.linalg.inv(A)))

[[ 1. -0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [39]:
# A @ A反矩陣 != 單位矩陣(I)
# A 為 singular 矩陣
# 第二行 = 第一行 + 1
# 第三行 = 第一行 + 2
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
             ])

print(np.around(A @ np.linalg.inv(A)))

[[ 0.  1. -0.]
 [ 0.  2. -1.]
 [ 0.  3.  2.]]


## 『內積』或稱『點積乘法』(Dot Product)

In [35]:
# 載入套件
import numpy as np

# 向量(Vector)
v = np.array([2,1])
s = np.array([-3,2])

#『內積』或稱『點積乘法』(Dot Product)
d = v @ s

print (d)

-4


## 計算夾角 θ

In [36]:
# 載入套件
import math
import numpy as np

# 向量(Vector)
v = np.array([2,1])
s = np.array([-3,2])

# 計算長度(magnitudes)
vMag = np.linalg.norm(v)
sMag = np.linalg.norm(s)

# 計算 cosine(θ)
cos = (v @ s) / (vMag * sMag)

# 計算 θ
theta = math.degrees(math.acos(cos))

print(theta)

119.74488129694222
