# Grid World迷宮之策略評估

In [1]:
# 載入相關套件
import numpy as np
from lib.envs.gridworld import GridworldEnv

In [2]:
# 環境
env = GridworldEnv()

In [3]:
# 策略評估函數
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    # 狀態值函數初始化
    V = np.zeros(env.nS)
    while True:
        delta = 0
        # 更新每個狀態值的函數
        for s in range(env.nS):
            v = 0
            # 計算每個行動後的狀態值函數
            for a, action_prob in enumerate(policy[s]):
                # 取得所有可能的下一狀態值
                for  prob, next_state, reward, done in env.P[s][a]:
                    # 狀態值函數公式，依照所有可能的下一狀態值函數加總 
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
            # 比較更新前後的差值，取最大值
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        # 若最大差值 < 門檻值，則停止評估
        if delta < theta:
            break
    return np.array(V)

In [4]:
# 隨機策略，機率均等
random_policy = np.ones([env.nS, env.nA]) / env.nA
# 評估
v = policy_eval(random_policy, env)

In [5]:
print("狀態值函數:")
print(v)
print("")

print("4x4 狀態值函數:")
print(v.reshape(env.shape))
print("")

狀態值函數:
[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569
   0.        ]

5x5 狀態值函數:
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]



In [6]:
# 驗證答案是否正確
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)